# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 闻新讯腾

on:
  workflow_dispatch:
  schedule:
     - cron: '*/3 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
          TXNEWS_SIGN: ${{ secrets.TXNEWS_SIGN }}
          TXNEWS_COOKIE: ${{ secrets.TXNEWS_COOKIE }}
          TXNEWS_VIDEO: ${{ secrets.TXNEWS_VIDEO }}
    steps:
      - name: Checkout
        run: |
          git clone ttps://github.com/ai1983/ziji.git ~/ziji
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.TXNEWS_SIGN
        run: |
          cd ~/ziji
          npm install
      - name: '运行 【闻新讯腾】'
        if: env.TXNEWS_SIGN
        run: |
          cd ~/ziji
          node Task/txnews.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}


    
